
version: 2

models:
    - name: my_first_dbt_model
      description: "A starter dbt model"
      columns:
          - name: id
            description: "The primary key for this table"
            tests:
                - unique
                - not_null

    - name: my_second_dbt_model_v0
      access: public
      #config:
       # contract:
        #  enforced: true
      columns:
          - name: id
            data_type: numeric
      latest_version: 0
      versions:
        - v: 0
        - v: 1
          columns:
          - include: all
          - name: another_column
            data_type: text